(()=>{
 const root=document.getElementById('agenda'); if(!root)return;
 const brand=document.querySelector('.top .brand');
 if(brand) brand.innerHTML='<span class="vLogo">V</span><span class="vWord">VİTRİN</span><span class="vTr">TR</span><span class="vFlag">🇹🇷</span>';
 const st=document.createElement('style');st.textContent=`
 :root{--g:#d7a64a;--g2:#f0cb74;--line:#8a6429;--bg:#050505;--card:#0c0b09;--txt:#f7f0e2;--mut:#b4a58a}
 body{background:#050505!important;color:var(--txt)!important}.top{height:80px!important;background:#050505!important;border-bottom:1px solid var(--line)!important;padding:8px 14px!important}.top .brand{display:flex!important;align-items:center!important;gap:8px!important;white-space:nowrap!important}.vLogo{font:700 54px/0.85 Georgia,serif;color:var(--g);border-bottom:1px solid var(--g);padding:0 5px 4px 0}.vWord{font:700 30px Georgia,serif;letter-spacing:2px;color:#dfb45e}.vTr{font-size:22px;font-weight:900;color:#e52b2b}.vFlag{font-size:20px}.topActions{gap:7px!important}.topActions .ib{width:42px!important;height:42px!important;border-radius:50%!important;background:#090909!important;border:1px solid var(--line)!important;color:var(--g)!important}.wrap{max-width:720px!important;padding:14px 18px 88px!important}.bottom{height:72px!important;background:#080705!important;border-top:1px solid var(--line)!important}.bottom button{color:#b9aa8c!important}.bottom button.on{color:#edc467!important}
 #agenda .gWrap{display:grid;gap:14px}.gHero{position:relative;overflow:hidden;min-height:200px;border:1px solid #b98936;border-radius:28px;padding:28px 24px;background:radial-gradient(circle at 82% 50%,rgba(214,160,57,.28),transparent 34%),linear-gradient(135deg,#070707,#15110b 58%,#050505)}.gHero h2{position:relative;z-index:2;margin:0 0 14px;font-size:35px;color:#e5b95f}.gHero p{position:relative;z-index:2;margin:0;font-size:18px;line-height:1.5}.gGlobe{position:absolute;right:-55px;top:18px;width:230px;height:230px;border:2px solid rgba(215,166,74,.42);border-radius:50%;opacity:.55;background:repeating-radial-gradient(circle,transparent 0 27px,rgba(215,166,74,.15) 28px 30px),repeating-linear-gradient(90deg,transparent 0 31px,rgba(215,166,74,.14) 32px 34px)}
 .gTabs,.gCats{display:flex;gap:10px;overflow-x:auto;scrollbar-width:none;-webkit-overflow-scrolling:touch;touch-action:pan-x}.gTabs::-webkit-scrollbar,.gCats::-webkit-scrollbar{display:none}.gTabs button,.gCats button{flex:0 0 auto;white-space:nowrap;border:1px solid #9b7433;background:#0d0c0a;color:#f5eee0;border-radius:999px;padding:12px 18px;font-weight:850;touch-action:manipulation}.gTabs button.on,.gCats button.on{background:linear-gradient(135deg,#f1c86d,#b67a27);color:#171009;border-color:#f1ca78}.gCatWrap{position:relative;overflow:hidden;padding-right:44px}.gCats{padding-right:52px}.gMore{position:absolute;right:0;top:0;width:42px;height:46px;border-radius:15px;background:#0d0b08;border:1px solid var(--line);color:#e9bc66;display:grid;place-items:center;font-size:27px;pointer-events:none}.gNote{font-size:12px;color:#9d8c6d}.gNote b{color:#d8aa50}.gBody{min-height:180px}.gLoading,.gEmpty{text-align:center;color:#b3a48b;padding:34px 10px}.gRetry{margin-top:12px;border:1px solid var(--line);background:#111;color:#e7bb64;border-radius:999px;padding:10px 16px;font-weight:800}.gList{display:grid;gap:10px}.gCard{display:grid;grid-template-columns:1fr 108px;min-height:112px;overflow:hidden;background:linear-gradient(135deg,#111,#070707);border:1px solid #815f28;border-radius:20px}.gCardBody{padding:15px 15px 12px;min-width:0}.gCard a{display:block;color:#f7f3eb;text-decoration:none;font-size:17px;font-weight:850;line-height:1.3}.gMeta{margin-top:10px;font-size:12px;color:#b7aa92;display:flex;gap:9px;flex-wrap:wrap}.gMeta .time{color:#d9aa4d}.gThumb{display:grid;place-items:center;border-left:1px solid #60481f;background:radial-gradient(circle,rgba(236,189,87,.20),transparent 46%),#0c0a07;font-size:38px}.gWeather{border:1px solid var(--line);border-radius:20px;padding:18px;background:#0d0b08}.gWeather b{color:#e8bd67}
 @media(max-width:520px){.top{height:76px!important;padding:7px 10px!important}.vLogo{font-size:45px}.vWord{font-size:26px}.vTr{font-size:19px}.vFlag{font-size:18px}.topActions .ib{width:38px!important;height:38px!important}.wrap{padding:12px 20px 84px!important}.gHero{min-height:185px;padding:24px 20px}.gHero h2{font-size:30px}.gHero p{font-size:16px}.gGlobe{width:205px;height:205px;right:-75px}.gCard{grid-template-columns:1fr 92px}.gCard a{font-size:16px}}
 `;document.head.appendChild(st);
 let scope='turkiye',cat='manset',city='Samsun',lat=null,lon=null,controller=null;
 root.innerHTML=`<div class="gWrap"><div class="gHero"><div class="gGlobe"></div><h2>🔥 VİTRİN Gündem</h2><p>Yakınınızdan Türkiye'ye,<br>Türkiye'den dünyaya tek ekranda.</p></div><div class="gTabs"><button data-s="local">📍 Yakınında</button><button class="on" data-s="turkiye">🇹🇷 Türkiye</button><button data-s="world">🌐 Dünya</button></div><div class="gCatWrap"><div class="gCats"><button class="on" data-c="manset">📰 Manşetler</button><button data-c="sondakika">🚨 Son Dakika</button><button data-c="spor">⚽ Spor</button><button data-c="magazin">🎬 Magazin</button><button data-c="muzik">🎵 Müzik</button><button data-c="ekonomi">💰 Ekonomi</button><button data-c="hava">🌦️ Hava</button><button data-c="teknoloji">💻 Teknoloji</button></div><div class="gMore">›</div></div><div class="gNote"><b>← Kategorileri kaydır →</b> · devamında daha fazla seçenek var</div><div id="gBody" class="gBody"></div></div>`;
 const body=root.querySelector('#gBody');
 const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const ago=d=>{const n=new Date(d);if(isNaN(n))return'';const m=Math.max(1,Math.round((Date.now()-n)/60000));return m<60?`${m} dk önce`:m<1440?`${Math.round(m/60)} sa önce`:`${Math.round(m/1440)} gün önce`};
 function setOn(sel,el){root.querySelectorAll(sel).forEach(x=>x.classList.toggle('on',x===el))}
 async function locate(){if(lat!=null)return;await new Promise(resolve=>{if(!navigator.geolocation)return resolve();navigator.geolocation.getCurrentPosition(p=>{lat=p.coords.latitude;lon=p.coords.longitude;resolve()},()=>resolve(),{timeout:3000,maximumAge:600000})})}
 async function weather(){body.innerHTML='<div class="gLoading">Hava durumu yükleniyor…</div>';await locate();if(lat==null){body.innerHTML='<div class="gEmpty">Konum izni gerekiyor.</div>';return}try{controller?.abort();controller=new AbortController();const t=setTimeout(()=>controller.abort(),6000);const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature,wind_speed_10m&timezone=auto`,{signal:controller.signal});clearTimeout(t);const j=await r.json();const c=j.current||{};body.innerHTML=`<div class="gWeather"><b>🌦️ ${esc(city)} Hava Durumu</b><div style="font-size:38px;font-weight:900;color:#e8bd67;margin:10px 0">${Math.round(c.temperature_2m)}°C</div><div>Hissedilen ${Math.round(c.apparent_temperature)}°C · Rüzgâr ${Math.round(c.wind_speed_10m)} km/sa</div></div>`}catch(e){body.innerHTML='<div class="gEmpty">Hava durumu alınamadı.<br><button class="gRetry" data-retry>Tekrar dene</button></div>'}}
 function thumb(){return cat==='spor'?'⚽':cat==='ekonomi'?'₺':cat==='teknoloji'?'💻':cat==='magazin'?'🎬':cat==='muzik'?'🎵':scope==='world'?'🌐':scope==='local'?'📍':'🇹🇷'}
 async function load(){
   if(cat==='hava')return weather();
   controller?.abort();controller=new AbortController();body.innerHTML='<div class="gLoading">Haberler yükleniyor…</div>';
   if(scope==='local')await locate();
   const t=setTimeout(()=>controller.abort(),7000);
   try{const r=await fetch(`/api/news?scope=${encodeURIComponent(scope)}&cat=${encodeURIComponent(cat)}&city=${encodeURIComponent(city)}&v=${Date.now()}`,{signal:controller.signal,cache:'no-store'});clearTimeout(t);if(!r.ok)throw new Error('HTTP '+r.status);const j=await r.json();const items=Array.isArray(j.items)?j.items:[];body.innerHTML=items.length?`<div class="gList">${items.slice(0,18).map(x=>`<article class="gCard"><div class="gCardBody"><a href="${esc(x.link)}" target="_blank" rel="noopener">${esc(x.title)}</a><div class="gMeta"><span>📰 ${esc(x.source)}</span><span class="time">◷ ${ago(x.pubDate)}</span></div></div><div class="gThumb">${thumb()}</div></article>`).join('')}</div>`:'<div class="gEmpty">Haber bulunamadı.<br><button class="gRetry" data-retry>Tekrar dene</button></div>'}catch(e){clearTimeout(t);if(e.name==='AbortError'&&body.querySelector('.gLoading'))body.innerHTML='<div class="gEmpty">Haber bağlantısı gecikti.<br><button class="gRetry" data-retry>Tekrar dene</button></div>';else if(e.name!=='AbortError')body.innerHTML='<div class="gEmpty">Haberler alınamadı.<br><button class="gRetry" data-retry>Tekrar dene</button></div>'}
 }
 root.addEventListener('click',e=>{const s=e.target.closest('[data-s]');if(s){e.preventDefault();scope=s.dataset.s;setOn('[data-s]',s);load();return}const c=e.target.closest('[data-c]');if(c){e.preventDefault();cat=c.dataset.c;setOn('[data-c]',c);c.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});load();return}if(e.target.closest('[data-retry]')){e.preventDefault();load()}});
 document.addEventListener('click',e=>{if(e.target.closest?.('[data-r="agenda"]'))setTimeout(load,50)});
 window.addEventListener('hashchange',()=>{if(location.hash==='#agenda')setTimeout(load,50)});
 if(location.hash==='#agenda'||root.classList.contains('on'))setTimeout(load,80);
 window.VitrinGundem={reload:load};
})();
