const SUPABASE_URL='https://wtkiozzylhvphxenrpwq.supabase.co';
const SUPABASE_KEY='sb_publishable_pDW5FSXya-HqQDl4pI4lAQ_Hdm7yptb';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let session=null,me=null,profiles={},currentChat=null,currentOther=null,msgChannel=null,notifChannel=null,historyLock=false,viewedProfileId=null;
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('on');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('on'),2200)}
function avatar(p){return p?.avatar_url?`<img src="${esc(p.avatar_url)}" alt="Profil">`:esc((p?.full_name||p?.username||'?')[0].toUpperCase())}
async function loadProfile(id){if(!id)return null;if(profiles[id])return profiles[id];const {data}=await sb.from('profiles').select('id,full_name,username,avatar_url,bio,city').eq('id',id).maybeSingle();if(data)profiles[id]=data;return data}
function showPage(name,push=true){if(!['home','reels','agenda','rooms','messages','profile'].includes(name))name='home';$$('.page').forEach(x=>x.classList.toggle('on',x.id===name));$$('[data-route]').forEach(x=>x.classList.toggle('on',x.dataset.route===name));if(push&&!historyLock)history.pushState({page:name},'',`#${name}`);if(name==='messages')loadChats();if(name==='profile')renderProfile(viewedProfileId||me?.id,false);scrollTo(0,0)}
document.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r){if(r.dataset.route==='profile')viewedProfileId=null;showPage(r.dataset.route)}const c=e.target.closest('[data-close]');if(c)$('#'+c.dataset.close).classList.remove('on');const p=e.target.closest('[data-profile]');if(p){viewedProfileId=p.dataset.profile;$('#notifModal').classList.remove('on');renderProfile(viewedProfileId)}});
window.addEventListener('popstate',()=>{if(!$('#chatPanel').hidden){closeChat(false);return}historyLock=true;showPage(location.hash.slice(1).split('/')[0]||'home',false);historyLock=false});
async function boot(){showPage(location.hash.slice(1).split('/')[0]||'home',false);const {data:{session:s}}=await sb.auth.getSession();session=s;if(session)me=await loadProfile(session.user.id);await Promise.all([loadFeed(),loadReels(),refreshBell()]);setupRealtime();sb.auth.onAuthStateChange(async(_e,s2)=>{session=s2;me=s2?await loadProfile(s2.user.id):null;await refreshBell();setupRealtime()})}
async function loadFeed(){const root=$('#feed');const [{data:posts,error:pe},{data:reels,error:re}]=await Promise.all([sb.from('posts').select('*').order('created_at',{ascending:false}).limit(50),sb.from('reels').select('*').eq('status','published').order('created_at',{ascending:false}).limit(30)]);if(pe||re){root.innerHTML='<div class="empty">Akış yüklenemedi.</div>';return}const items=[...(posts||[]).map(x=>({...x,_k:'p'})),...(reels||[]).map(x=>({...x,_k:'r'}))].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));await Promise.all([...new Set(items.map(x=>x.user_id))].map(loadProfile));root.innerHTML=items.length?items.map(feedHtml).join(''):'<div class="empty">Henüz gönderi yok.</div>';setupAutoPlay()}
function feedHtml(x){const p=profiles[x.user_id]||{};return `<article class="card"><div class="head clickable" data-profile="${x.user_id}"><div class="av">${avatar(p)}</div><div class="meta"><b>${esc(p.full_name||'Üye')}</b><span class="muted">@${esc(p.username||'uye')}</span></div></div>${x._k==='p'?`<p>${esc(x.body||'')}</p>${x.image_url?`<img class="media" loading="lazy" src="${esc(x.image_url)}">`:''}`:`<p>🎬 ${esc(x.caption||'BULUT Reels')}</p><video class="media reel" src="${esc(x.video_url)}" playsinline muted preload="metadata" controls></video>`}</article>`}
async function loadReels(){const root=$('#reelFeed');const {data,error}=await sb.from('reels').select('*').eq('status','published').order('created_at',{ascending:false}).limit(40);if(error){root.innerHTML='<div class="empty">Reels yüklenemedi.</div>';return}await Promise.all([...new Set((data||[]).map(x=>x.user_id))].map(loadProfile));root.innerHTML=(data||[]).map(x=>feedHtml({...x,_k:'r'})).join('')||'<div class="empty">Henüz Reel yok.</div>';setupAutoPlay()}
function setupAutoPlay(){const vids=$$('video.reel');if(!vids.length)return;const ob=new IntersectionObserver(entries=>{const best=entries.filter(e=>e.isIntersecting&&e.intersectionRatio>.62).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(best){vids.forEach(v=>{if(v!==best.target&&!v.paused)v.pause()});best.target.play().catch(()=>{})}entries.forEach(e=>{if(e.intersectionRatio<.25&&!e.target.paused)e.target.pause()})},{threshold:[0,.25,.62,.8,1]});vids.forEach(v=>ob.observe(v))}
async function renderProfile(id,push=true){if(!id)return toast('Giriş yapmalısınız.');const p=await loadProfile(id);if(!p)return toast('Profil bulunamadı.');viewedProfileId=id;if(push)showPage('profile');else{$$('.page').forEach(x=>x.classList.toggle('on',x.id==='profile'))}let action='';if(session&&session.user.id!==id){const [{data:mine},{data:back}]=await Promise.all([sb.from('follows').select('follower_id').eq('follower_id',session.user.id).eq('following_id',id).maybeSingle(),sb.from('follows').select('follower_id').eq('follower_id',id).eq('following_id',session.user.id).maybeSingle()]);const mutual=!!mine&&!!back;action=`<button class="${mine?'outline':'primary'}" data-follow="${id}">${mine?'Takibi Bırak':'Takip Et'}</button> <button class="outline" data-message-person="${id}">${mutual?'💬 Mesajlara Git':'💬 Sohbet İsteği'}</button>`}$('#profileBox').innerHTML=`<div class="av">${avatar(p)}</div><h2>${esc(p.full_name||'Üye')}</h2><div class="muted">@${esc(p.username||'uye')}${p.city?' · '+esc(p.city):''}</div><p>${esc(p.bio||'Bulut’a yeni katıldı ☁️')}</p>${action}`;$$('[data-follow]').forEach(b=>b.onclick=()=>toggleFollow(b.dataset.follow));$$('[data-message-person]').forEach(b=>b.onclick=()=>messagePerson(b.dataset.messagePerson))}
async function toggleFollow(target){if(!session)return toast('Giriş yapmalısınız.');const {data:f}=await sb.from('follows').select('follower_id').eq('follower_id',session.user.id).eq('following_id',target).maybeSingle();const {error}=f?await sb.from('follows').delete().eq('follower_id',session.user.id).eq('following_id',target):await sb.from('follows').insert({follower_id:session.user.id,following_id:target});if(error)return toast('Takip işlemi yapılamadı.');await ensureMutualChat(target);await renderProfile(target,false);await refreshBell()}
async function mutualWith(target){const [{data:a},{data:b}]=await Promise.all([sb.from('follows').select('follower_id').eq('follower_id',session.user.id).eq('following_id',target).maybeSingle(),sb.from('follows').select('follower_id').eq('follower_id',target).eq('following_id',session.user.id).maybeSingle()]);return !!a&&!!b}
async function chatRowsWith(target){const {data}=await sb.from('chat_requests').select('*').or(`and(sender_id.eq.${session.user.id},receiver_id.eq.${target}),and(sender_id.eq.${target},receiver_id.eq.${session.user.id})`).order('created_at',{ascending:true});return data||[]}
async function ensureMutualChat(target){if(!session||!(await mutualWith(target)))return null;const rows=await chatRowsWith(target);let accepted=rows.find(x=>x.status==='accepted');if(accepted)return accepted;let row=rows[0];if(row){const {data,error}=await sb.from('chat_requests').update({status:'accepted'}).eq('id',row.id).select('*').single();if(!error)return data}const {data,error}=await sb.from('chat_requests').insert({sender_id:session.user.id,receiver_id:target,status:'accepted'}).select('*').single();return error?null:data}
async function messagePerson(target){if(!session)return toast('Giriş yapmalısınız.');if(await mutualWith(target)){const r=await ensureMutualChat(target);if(!r)return toast('Sohbet açılamadı.');showPage('messages');return openChat(r.id)}const rows=await chatRowsWith(target);const pending=rows.find(x=>x.status==='pending');if(pending)return toast('Sohbet isteğiniz bekliyor.');const {error}=await sb.from('chat_requests').insert({sender_id:session.user.id,receiver_id:target,status:'pending'});toast(error?'Sohbet isteği gönderilemedi.':'Sohbet isteği gönderildi ☁️')}
async function allChatRows(){const {data,error}=await sb.from('chat_requests').select('*').or(`sender_id.eq.${session.user.id},receiver_id.eq.${session.user.id}`).order('created_at',{ascending:false});if(error)throw error;return data||[]}
async function acceptedChats(){const rows=await allChatRows(),seen=new Set(),out=[];for(const r of rows.filter(x=>x.status==='accepted')){const other=r.sender_id===session.user.id?r.receiver_id:r.sender_id;if(seen.has(other))continue;seen.add(other);out.push({...r,_other:other})}return out}
async function loadChats(){const root=$('#chatList');if(!session){root.innerHTML='<div class="empty">Mesajları görmek için giriş yapın.</div>';return}root.innerHTML='<div class="loading">Yükleniyor…</div>';try{const rows=await allChatRows();const seen=new Set(),chats=[];for(const r of rows.filter(x=>x.status==='accepted')){const other=r.sender_id===session.user.id?r.receiver_id:r.sender_id;if(!seen.has(other)){seen.add(other);chats.push({...r,_other:other})}}const pending=rows.filter(x=>x.status==='pending');await Promise.all([...new Set([...chats.map(x=>x._other),...pending.map(r=>r.sender_id===session.user.id?r.receiver_id:r.sender_id)])].map(loadProfile));let html='';if(chats.length){html+='<div class="sectionTitle">Sohbetler</div>'+chats.map(r=>{const p=profiles[r._other]||{};return `<div class="row"><div class="av clickable" data-profile="${r._other}">${avatar(p)}</div><div class="clickable" data-profile="${r._other}"><b>${esc(p.full_name||'Üye')}</b><div class="muted">@${esc(p.username||'uye')}</div></div><button class="primary" data-chat="${r.id}">Aç</button></div>`}).join('')}if(pending.length){html+='<div class="sectionTitle">Sohbet İstekleri</div>'+pending.map(r=>{const incoming=r.receiver_id===session.user.id,other=r.sender_id===session.user.id?r.receiver_id:r.sender_id,p=profiles[other]||{};return `<div class="row"><div class="av" data-profile="${other}">${avatar(p)}</div><div><b>${esc(p.full_name||'Üye')}</b><div class="muted">${incoming?'Size sohbet isteği gönderdi':'İstek gönderildi'}</div></div>${incoming?`<div><button class="primary" data-request="${r.id}" data-status="accepted">Kabul</button> <button class="outline" data-request="${r.id}" data-status="rejected">Reddet</button></div>`:'<span class="muted">Bekliyor</span>'}</div>`}).join('')}root.innerHTML=html||'<div class="empty">Henüz sohbet yok.</div>';$$('[data-chat]').forEach(b=>b.onclick=()=>openChat(b.dataset.chat));$$('[data-request]').forEach(b=>b.onclick=()=>updateRequest(b.dataset.request,b.dataset.status))}catch(e){console.error(e);root.innerHTML='<div class="empty">Sohbetler yüklenemedi.</div>'}}
async function updateRequest(id,status){const {error}=await sb.from('chat_requests').update({status}).eq('id',id);if(error)return toast('İstek güncellenemedi.');await loadChats();await refreshBell()}
async function openChat(id){if(!session)return;const {data:r,error}=await sb.from('chat_requests').select('*').eq('id',id).maybeSingle();if(error||!r||r.status!=='accepted')return toast('Sohbet açılamadı.');const other=r.sender_id===session.user.id?r.receiver_id:r.sender_id;currentChat=r;currentOther=await loadProfile(other);$('#chatAvatar').innerHTML=avatar(currentOther);$('#chatName').textContent=currentOther?.full_name||'Üye';$('#chatUser').textContent='@'+(currentOther?.username||'uye');$('#chatListCard').hidden=true;$('#chatPanel').hidden=false;if(!location.hash.includes('/chat/'))history.pushState({chat:id},'',`#messages/chat/${id}`);await loadMessages(true);if(msgChannel)await sb.removeChannel(msgChannel);msgChannel=sb.channel('clean-chat-'+id).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`chat_request_id=eq.${id}`},()=>loadMessages(true)).subscribe()}
async function loadMessages(markRead){if(!currentChat)return;const {data,error}=await sb.from('messages').select('*').eq('chat_request_id',currentChat.id).order('created_at',{ascending:true}).limit(500);if(error)return;const rows=data||[];$('#chatMessages').innerHTML=rows.map(m=>{const mine=m.sender_id===session.user.id,t=new Date(m.created_at).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'});return `<div class="bubble ${mine?'mine':''}">${esc(m.body)}<div class="bt">${t}${mine&&m.read_at?' · Görüldü':''}</div></div>`}).join('')||'<div class="empty">İlk mesajı siz gönderin.</div>';$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight;if(markRead){const unread=rows.filter(m=>m.sender_id!==session.user.id&&!m.read_at).map(m=>m.id);if(unread.length)await sb.from('messages').update({read_at:new Date().toISOString(),delivered_at:new Date().toISOString()}).in('id',unread);await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',session.user.id).eq('actor_id',currentOther.id).eq('type','message').is('read_at',null);await refreshBell()}}
$('#chatForm').onsubmit=async e=>{e.preventDefault();const body=$('#chatInput').value.trim();if(!body||!currentChat)return;const {error}=await sb.from('messages').insert({chat_request_id:currentChat.id,sender_id:session.user.id,body});if(error)return toast('Mesaj gönderilemedi.');$('#chatInput').value='';await loadMessages(false)};
async function closeChat(useBack=true){if(msgChannel){await sb.removeChannel(msgChannel);msgChannel=null}currentChat=null;currentOther=null;$('#chatPanel').hidden=true;$('#chatListCard').hidden=false;await loadChats();if(useBack&&location.hash.includes('/chat/'))history.back()}
$('#chatBack').onclick=()=>closeChat(true);$('#refreshChats').onclick=loadChats;$('#chatAvatar').onclick=()=>currentOther&&(viewedProfileId=currentOther.id,renderProfile(currentOther.id));$('#chatIdentity').onclick=()=>currentOther&&(viewedProfileId=currentOther.id,renderProfile(currentOther.id));
async function unreadState(){if(!session)return{messageRows:[],senders:[],other:[],requestRows:[]};const [{data:chatRows},{data:notifs},{data:reqs}]=await Promise.all([sb.from('chat_requests').select('id,sender_id,receiver_id,status').or(`sender_id.eq.${session.user.id},receiver_id.eq.${session.user.id}`).eq('status','accepted'),sb.from('notifications').select('id,actor_id,type,read_at,created_at').eq('user_id',session.user.id).is('read_at',null).order('created_at',{ascending:false}),sb.from('chat_requests').select('id,sender_id,receiver_id,status,created_at').eq('receiver_id',session.user.id).eq('status','pending')]);const chatIds=(chatRows||[]).map(r=>r.id);let messageRows=[];if(chatIds.length){const {data:msgs}=await sb.from('messages').select('id,chat_request_id,sender_id,read_at,created_at').in('chat_request_id',chatIds).neq('sender_id',session.user.id).is('read_at',null);messageRows=msgs||[]}const senders=[...new Set(messageRows.map(x=>x.sender_id))],other=(notifs||[]).filter(n=>n.type!=='message'),requestRows=reqs||[];return{messageRows,senders,other,requestRows}}
async function refreshBell(){const badge=$('#badge'),bell=$('#bell');if(!session){badge.hidden=true;bell.classList.remove('bellRing');return}const s=await unreadState();const actorEvents=new Set(s.other.map(n=>`${n.type}:${n.actor_id}`));const total=s.senders.length+actorEvents.size+s.requestRows.length;badge.textContent=total>99?'99+':String(total);badge.hidden=!total;bell.classList.toggle('bellRing',total>0)}
$('#bell').onclick=async()=>{if(!session)return toast('Giriş yapmalısınız.');$('#notifModal').classList.add('on');await renderNotifications()};
function notifText(type){if(type==='follow')return 'sizi takip etti.';if(type==='chat_accepted')return 'sohbet isteğinizi kabul etti.';if(type==='chat_rejected')return 'sohbet isteğinizi reddetti.';if(type.includes('reel')&&type.includes('like'))return 'Reel’inizi beğendi.';if(type.includes('reel')&&type.includes('comment'))return 'Reel’inize yorum yaptı.';if(type.includes('like'))return 'gönderinizi beğendi.';if(type.includes('comment'))return 'gönderinize yorum yaptı.';return 'etkileşimde bulundu.'}
async function renderNotifications(){const root=$('#notifContent');root.innerHTML='<div class="loading">Yükleniyor…</div>';const s=await unreadState();const allIds=[...new Set([...s.senders,...s.other.map(n=>n.actor_id),...s.requestRows.map(r=>r.sender_id)])];await Promise.all(allIds.map(loadProfile));const eventGroups=new Map();for(const n of s.other){const k=`${n.type}:${n.actor_id}`;if(!eventGroups.has(k))eventGroups.set(k,n)}let html=`<div class="summary">💬 <b>${s.messageRows.length} yeni mesaj</b> · ${s.senders.length} kişiden<br>👤 <b>${s.requestRows.length} sohbet isteği</b><br>🔔 <b>${eventGroups.size} takip/etkileşim bildirimi</b></div>`;if(s.senders.length){html+='<div class="sectionTitle">Yeni Mesajlar</div>'+s.senders.map(id=>{const p=profiles[id]||{},count=s.messageRows.filter(m=>m.sender_id===id).length;return `<div class="row"><div class="av clickable" data-profile="${id}">${avatar(p)}</div><div class="clickable" data-profile="${id}"><b>${esc(p.full_name||'Üye')}</b><div class="muted">${count} yeni mesaj</div></div><button class="primary" data-open-person="${id}">Mesajlar</button></div>`}).join('')}if(s.requestRows.length){html+='<div class="sectionTitle">Sohbet İstekleri</div>'+s.requestRows.map(r=>{const p=profiles[r.sender_id]||{};return `<div class="row"><div class="av" data-profile="${r.sender_id}">${avatar(p)}</div><div><b>${esc(p.full_name||'Üye')}</b><div class="muted">Sohbet isteği gönderdi</div></div><button class="primary" data-request-modal="${r.id}">Mesajlara Git</button></div>`}).join('')}if(eventGroups.size){html+='<div class="sectionTitle">Takip ve Etkileşimler</div>'+[...eventGroups.values()].map(n=>{const p=profiles[n.actor_id]||{};return `<div class="row"><div class="av clickable" data-profile="${n.actor_id}">${avatar(p)}</div><div><b>${esc(p.full_name||'Üye')}</b> ${notifText(n.type)}</div><button class="outline" data-profile="${n.actor_id}">Profil</button></div>`}).join('')}if(!s.senders.length&&!s.requestRows.length&&!eventGroups.size)html='<div class="empty">Yeni bildiriminiz yok.</div>';root.innerHTML=html;$$('[data-open-person]').forEach(b=>b.onclick=()=>openPersonChat(b.dataset.openPerson));$$('[data-request-modal]').forEach(b=>b.onclick=()=>{$('#notifModal').classList.remove('on');showPage('messages')});if(s.other.length){await sb.from('notifications').update({read_at:new Date().toISOString()}).in('id',s.other.map(n=>n.id));await refreshBell()}}
async function openPersonChat(otherId){const chats=await acceptedChats(),r=chats.find(x=>x._other===otherId);if(!r)return toast('Bu kişiyle açık sohbet bulunamadı.');$('#notifModal').classList.remove('on');showPage('messages');await openChat(r.id)}
function setupRealtime(){if(notifChannel){sb.removeChannel(notifChannel);notifChannel=null}if(!session)return;notifChannel=sb.channel('clean-notifs-'+session.user.id).on('postgres_changes',{event:'*',schema:'public',table:'notifications',filter:`user_id=eq.${session.user.id}`},refreshBell).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},refreshBell).on('postgres_changes',{event:'*',schema:'public',table:'chat_requests',filter:`receiver_id=eq.${session.user.id}`},refreshBell).subscribe()}
boot();