(()=>{
 const root=document.getElementById('agenda'); if(!root)return;
 const st=document.createElement('style');st.textContent=`
 #agenda .gWrap{display:grid;gap:12px}.gHero{background:linear-gradient(135deg,#10233f,#2d8cff);color:#fff;border-radius:24px;padding:18px}.gTabs,.gCats{display:flex;gap:8px;overflow:auto;padding-bottom:3px}.gTabs button,.gCats button{white-space:nowrap;border:1px solid #dfeaf6;background:#fff;border-radius:999px;padding:10px 13px;font-weight:800}.gTabs button.on,.gCats button.on{background:#2d8cff;color:#fff;border-color:#2d8cff}.gCard{background:#fff;border:1px solid #dfeaf6;border-radius:18px;padding:14px;margin-bottom:10px}.gCard a{color:#10233f;text-decoration:none;font-weight:850;line-height:1.35}.gMeta{font-size:12px;color:#71829a;margin-top:7px;display:flex;gap:8px;flex-wrap:wrap}.gWeather{background:linear-gradient(135deg,#eff9ff,#dff3ff);border:1px solid #ccecff;border-radius:20px;padding:14px}.gEmpty{text-align:center;color:#71829a;padding:28px 10px}
 `;document.head.appendChild(st);
 let scope='turkiye',cat='manset',city='Samsun',lat=null,lon=null;
 root.innerHTML=`<div class="gWrap"><div class="gHero"><h2 style="margin:0 0 6px">🔥 BULUT Gündem</h2><div style="opacity:.9">Yakınınızdan Türkiye'ye, Türkiye'den dünyaya tek ekranda.</div></div><div class="gTabs"><button data-s="local">📍 Yakınında</button><button class="on" data-s="turkiye">🇹🇷 Türkiye</button><button data-s="world">🌍 Dünya</button></div><div class="gCats"><button class="on" data-c="manset">📰 Manşetler</button><button data-c="sondakika">🚨 Son Dakika</button><button data-c="spor">⚽ Spor</button><button data-c="magazin">🎬 Magazin</button><button data-c="ekonomi">💰 Ekonomi</button><button data-c="hava">🌦️ Hava</button><button data-c="teknoloji">💻 Teknoloji</button></div><div id="gBody"><div class="gEmpty">Gündem yükleniyor…</div></div></div>`;
 const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const ago=d=>{const n=new Date(d);if(isNaN(n))return '';const m=Math.max(1,Math.round((Date.now()-n)/60000));return m<60?`${m} dk önce`:m<1440?`${Math.round(m/60)} sa önce`:`${Math.round(m/1440)} gün önce`};
 async function locate(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve();navigator.geolocation.getCurrentPosition(async p=>{lat=p.coords.latitude;lon=p.coords.longitude;try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lon}`,{headers:{'Accept-Language':'tr'}});const j=await r.json();city=j.address?.city||j.address?.town||j.address?.province||j.address?.state||city}catch{}resolve()},()=>resolve(),{enableHighAccuracy:false,timeout:5000,maximumAge:600000})})}
 async function weather(){const b=document.getElementById('gBody');b.innerHTML='<div class="gEmpty">Hava durumu yükleniyor…</div>';if(lat==null||lon==null)await locate();if(lat==null||lon==null){b.innerHTML='<div class="gEmpty">Hava durumu için konum izni gerekiyor.</div>';return}try{const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&timezone=auto`);const j=await r.json();const c=j.current||{};b.innerHTML=`<div class="gWeather"><b>🌦️ ${esc(city)} Hava Durumu</b><div style="font-size:34px;font-weight:900;margin:8px 0">${Math.round(c.temperature_2m)}°C</div><div>Hissedilen ${Math.round(c.apparent_temperature)}°C · Rüzgâr ${Math.round(c.wind_speed_10m)} km/sa</div><div class="gMeta">Kaynak: Open-Meteo · Güncel ölçüm</div></div>`}catch{b.innerHTML='<div class="gEmpty">Hava durumu alınamadı.</div>'}}
 async function load(){if(cat==='hava')return weather();const b=document.getElementById('gBody');b.innerHTML='<div class="gEmpty">Haberler yükleniyor…</div>';if(scope==='local'&&!lat)await locate();try{const r=await fetch(`/api/news?scope=${encodeURIComponent(scope)}&cat=${encodeURIComponent(cat)}&city=${encodeURIComponent(city)}`);const j=await r.json();const it=j.items||[];b.innerHTML=it.length?it.map(x=>`<article class="gCard"><a href="${esc(x.link)}" target="_blank" rel="noopener">${esc(x.title)}</a><div class="gMeta"><span>📰 ${esc(x.source)}</span><span>🕒 ${ago(x.pubDate)}</span>${scope==='local'?`<span>📍 ${esc(city)}</span>`:''}</div></article>`).join(''):'<div class="gEmpty">Bu bölümde şu anda haber bulunamadı.</div>'}catch{b.innerHTML='<div class="gEmpty">Haberler şu anda alınamıyor.</div>'}}
 root.querySelectorAll('[data-s]').forEach(x=>x.onclick=()=>{scope=x.dataset.s;root.querySelectorAll('[data-s]').forEach(y=>y.classList.toggle('on',y===x));load()});
 root.querySelectorAll('[data-c]').forEach(x=>x.onclick=()=>{cat=x.dataset.c;root.querySelectorAll('[data-c]').forEach(y=>y.classList.toggle('on',y===x));load()});
 load();
 window.BulutGundem={reload:load};
})();
