(()=>{
 const root=document.getElementById('agenda'); if(!root)return;

 /* VİTRİN marka dönüşümü: sadece marka ve renkler, mevcut çalışan arayüz yapısına dokunma */
 const brand=document.querySelector('.top .brand');
 if(brand){
   brand.innerHTML='<span class="vLogo" aria-hidden="true">V</span><span class="vWord">VİTRİN</span><span class="vTr">TR</span><span class="vFlag">🇹🇷</span>';
 }
 document.title='VİTRİN — Sosyal Ağ';
 const themeMeta=document.querySelector('meta[name="theme-color"]');
 if(themeMeta)themeMeta.setAttribute('content','#090806');

 const st=document.createElement('style');st.textContent=`
 :root{--vGold:#d8a64a;--vGold2:#f0c96f;--vLine:#6f5227;--vBg:#080806;--vCard:#11100d;--vText:#f4efe6;--vMuted:#b5a78f}
 body{background:linear-gradient(#0b0a08,#070705)!important;color:var(--vText)!important}
 .top{background:rgba(8,8,6,.96)!important;border-bottom-color:var(--vLine)!important}
 .brand{gap:7px!important}.vLogo{font:700 40px/1 Georgia,'Times New Roman',serif;color:var(--vGold);text-shadow:0 1px 0 #f6dda5}.vWord{font:700 24px/1 Georgia,'Times New Roman',serif;letter-spacing:1.5px;color:var(--vGold2)}.vTr{color:#e30a17;font-size:18px;font-weight:900}.vFlag{font-size:18px}
 .ib{background:#15130f!important;border:1px solid var(--vLine)!important;color:var(--vGold2)!important}
 .card{background:linear-gradient(145deg,#12110e,#0d0c0a)!important;border-color:var(--vLine)!important;box-shadow:0 10px 28px rgba(0,0,0,.28)!important;color:var(--vText)!important}
 .muted,.tiny,.hint,.post .head small,.trend small,.stats{color:var(--vMuted)!important}
 .ring{border-color:var(--vGold)!important}.ask,.pa button,.room,.file,.commentItem,.privacyBox{background:#15130f!important;border-color:var(--vLine)!important;color:var(--vText)!important}
 .primary{background:linear-gradient(135deg,var(--vGold2),#a96e20)!important;color:#171009!important}.outline{background:#12110e!important;border-color:var(--vLine)!important;color:var(--vGold2)!important}
 .bottom{background:rgba(8,8,6,.98)!important;border-top-color:var(--vLine)!important}.bottom button{color:#b6a98f!important}.bottom button.on{color:var(--vGold2)!important}
 .chatHead,.chatComposer,.box,.searchBox{background:#11100d!important;color:var(--vText)!important}.chatMessages{background:linear-gradient(#0d0c0a,#090806)!important}.bubble{background:#15130f!important;border-color:var(--vLine)!important;color:var(--vText)!important}.bubble.mine{background:linear-gradient(135deg,var(--vGold2),#a96e20)!important;color:#171009!important}
 input,textarea{background:#0e0d0b!important;border-color:var(--vLine)!important;color:var(--vText)!important}.cover{background:linear-gradient(135deg,#2b2112,#8e672a,#16120c)!important}
 #agenda{overflow-x:hidden;max-width:100%}#agenda .gWrap{display:grid;gap:12px;min-width:0;max-width:100%}#agenda .gWrap>*{min-width:0;max-width:100%}
 .gHero{background:linear-gradient(135deg,#15110a,#6e4b1d);color:#fff;border:1px solid var(--vLine);border-radius:24px;padding:18px}.gTabs{display:flex;gap:8px;overflow:auto;padding-bottom:3px;scrollbar-width:none;max-width:100%;overscroll-behavior-x:contain}.gTabs::-webkit-scrollbar{display:none}.gTabs button,.gCats button{white-space:nowrap;border:1px solid var(--vLine);background:#11100d;color:var(--vText);border-radius:999px;padding:10px 13px;font-weight:800;flex:0 0 auto}.gTabs button.on,.gCats button.on{background:linear-gradient(135deg,var(--vGold2),#a96e20);color:#171009;border-color:var(--vGold2)}
 .gCatWrap{position:relative;overflow:hidden;max-width:100%;padding-right:34px}.gCats{display:flex;gap:8px;overflow-x:auto;overflow-y:hidden;padding:0 44px 4px 0;scrollbar-width:none;max-width:100%;min-width:0;-webkit-overflow-scrolling:touch;overscroll-behavior-x:contain;touch-action:pan-x;scroll-snap-type:x proximity}.gCats::-webkit-scrollbar{display:none}.gCats button{scroll-snap-align:start}.gMoreHint{position:absolute;right:0;top:50%;transform:translateY(-54%);z-index:4;width:38px;height:44px;display:grid;place-items:center;border-radius:15px 0 0 15px;background:linear-gradient(90deg,rgba(8,8,6,.72),#0d0c0a 38%);color:var(--vGold2);transition:.2s;pointer-events:none}.gMoreHint .arr{display:grid;place-items:center;width:29px;height:29px;border-radius:50%;background:var(--vGold);color:#171009;font-size:22px;font-weight:900;box-shadow:0 4px 12px rgba(216,166,74,.25);animation:gArrow 1s ease-in-out infinite}.gMoreHint.hide{opacity:0}.gCatNote{font-size:11px;color:var(--vMuted);margin-top:-5px;padding-left:4px}.gCatNote b{color:var(--vGold2)}@keyframes gArrow{0%,100%{transform:translateX(0)}50%{transform:translateX(3px)}}
 .gCard{background:#11100d;border:1px solid var(--vLine);border-radius:18px;padding:14px;margin-bottom:10px}.gCard a{color:var(--vText);text-decoration:none;font-weight:850;line-height:1.35}.gMeta{font-size:12px;color:var(--vMuted);margin-top:7px;display:flex;gap:8px;flex-wrap:wrap}.gWeather{background:linear-gradient(135deg,#17130d,#0e0d0b);border:1px solid var(--vLine);border-radius:20px;padding:14px}.gEmpty{text-align:center;color:var(--vMuted);padding:28px 10px}
 @media(max-width:420px){.brand{gap:5px!important}.vLogo{font-size:36px}.vWord{font-size:21px}.vTr{font-size:16px}.vFlag{font-size:16px}}
 `;document.head.appendChild(st);

 /* Gündem: çalışan önceki işleyiş korunmuştur */
 let scope='turkiye',cat='manset',city='Samsun',lat=null,lon=null,loaded=false,loading=false;
 root.innerHTML=`<div class="gWrap"><div class="gHero"><h2 style="margin:0 0 6px">🔥 VİTRİN Gündem</h2><div style="opacity:.9">Yakınınızdan Türkiye'ye, Türkiye'den dünyaya tek ekranda.</div></div><div class="gTabs"><button data-s="local">📍 Yakınında</button><button class="on" data-s="turkiye">🇹🇷 Türkiye</button><button data-s="world">🌍 Dünya</button></div><div class="gCatWrap"><div class="gCats" id="gCats"><button class="on" data-c="manset">📰 Manşetler</button><button data-c="sondakika">🚨 Son Dakika</button><button data-c="spor">⚽ Spor</button><button data-c="magazin">🎬 Magazin</button><button data-c="muzik">🎵 Müzik</button><button data-c="ekonomi">💰 Ekonomi</button><button data-c="hava">🌦️ Hava</button><button data-c="teknoloji">💻 Teknoloji</button></div><div class="gMoreHint" id="gMoreHint"><span class="arr">›</span></div></div><div class="gCatNote"><b>← Kategorileri kaydır →</b> · devamında daha fazla seçenek var</div><div id="gBody"><div class="gEmpty">Gündem'e girdiğinizde haberler yüklenecek.</div></div></div>`;
 const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const ago=d=>{const n=new Date(d);if(isNaN(n))return '';const m=Math.max(1,Math.round((Date.now()-n)/60000));return m<60?`${m} dk önce`:m<1440?`${Math.round(m/60)} sa önce`:`${Math.round(m/1440)} gün önce`};
 const cats=document.getElementById('gCats'),hint=document.getElementById('gMoreHint');
 function updateHint(){if(!cats||!hint)return;const more=cats.scrollWidth>cats.clientWidth+8&&cats.scrollLeft+cats.clientWidth<cats.scrollWidth-10;hint.classList.toggle('hide',!more)}
 cats?.addEventListener('scroll',updateHint,{passive:true});window.addEventListener('resize',updateHint);setTimeout(updateHint,120);
 async function locate(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve();navigator.geolocation.getCurrentPosition(async p=>{lat=p.coords.latitude;lon=p.coords.longitude;try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lon}`,{headers:{'Accept-Language':'tr'}});const j=await r.json();city=j.address?.city||j.address?.town||j.address?.province||j.address?.state||city}catch{}resolve()},()=>resolve(),{enableHighAccuracy:false,timeout:5000,maximumAge:600000})})}
 async function weather(){const b=document.getElementById('gBody');b.innerHTML='<div class="gEmpty">Hava durumu yükleniyor…</div>';if(lat==null||lon==null)await locate();if(lat==null||lon==null){b.innerHTML='<div class="gEmpty">Hava durumu için konum izni gerekiyor.</div>';return}try{const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&timezone=auto`);const j=await r.json();const c=j.current||{};b.innerHTML=`<div class="gWeather"><b>🌦️ ${esc(city)} Hava Durumu</b><div style="font-size:34px;font-weight:900;margin:8px 0;color:var(--vGold2)">${Math.round(c.temperature_2m)}°C</div><div>Hissedilen ${Math.round(c.apparent_temperature)}°C · Rüzgâr ${Math.round(c.wind_speed_10m)} km/sa</div><div class="gMeta">Kaynak: Open-Meteo · Güncel ölçüm</div></div>`}catch{b.innerHTML='<div class="gEmpty">Hava durumu alınamadı.</div>'}}
 async function load(){if(loading)return;loading=true;loaded=true;try{if(cat==='hava')return await weather();const b=document.getElementById('gBody');b.innerHTML='<div class="gEmpty">Haberler yükleniyor…</div>';if(scope==='local'&&!lat)await locate();try{const r=await fetch(`/api/news?scope=${encodeURIComponent(scope)}&cat=${encodeURIComponent(cat)}&city=${encodeURIComponent(city)}`);const j=await r.json();const it=j.items||[];b.innerHTML=it.length?it.map(x=>`<article class="gCard"><a href="${esc(x.link)}" target="_blank" rel="noopener">${esc(x.title)}</a><div class="gMeta"><span>📰 ${esc(x.source)}</span><span>🕒 ${ago(x.pubDate)}</span>${scope==='local'?`<span>📍 ${esc(city)}</span>`:''}</div></article>`).join(''):'<div class="gEmpty">Bu bölümde şu anda haber bulunamadı.</div>'}catch{b.innerHTML='<div class="gEmpty">Haberler şu anda alınamıyor.</div>'}}finally{loading=false}}
 const ensureLoaded=()=>{if(!loaded)load()};
 root.querySelectorAll('[data-s]').forEach(x=>x.onclick=()=>{scope=x.dataset.s;root.querySelectorAll('[data-s]').forEach(y=>y.classList.toggle('on',y===x));load()});
 root.querySelectorAll('[data-c]').forEach(x=>x.onclick=()=>{cat=x.dataset.c;root.querySelectorAll('[data-c]').forEach(y=>y.classList.toggle('on',y===x));x.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});load()});
 document.addEventListener('click',e=>{if(e.target.closest?.('[data-r="agenda"]'))setTimeout(ensureLoaded,0)},{passive:true});
 window.addEventListener('hashchange',()=>{if(location.hash==='#agenda')ensureLoaded()});
 if(location.hash==='#agenda'||root.classList.contains('on'))ensureLoaded();
 window.BulutGundem={reload:load};
})();
