(function(){
  if(window.__vitrinLiveFix3)return;window.__vitrinLiveFix3=true;
  const gifts=[
    {code:'gul',icon:'🌹',name:'Gül',tl:100},{code:'kahve',icon:'☕',name:'Kahve',tl:250},{code:'kalp',icon:'💖',name:'Parlayan Kalp',tl:500},{code:'yildiz',icon:'⭐',name:'Altın Yıldız',tl:1000},{code:'tac',icon:'👑',name:'Altın Taç',tl:2500},{code:'roket',icon:'🚀',name:'VİTRİN Roketi',tl:5000},{code:'elmas',icon:'💎',name:'Mavi Elmas',tl:10000},{code:'kraliyet',icon:'👑💎',name:'Kraliyet Elması',tl:25000}
  ];
  let stream=null,currentRoom=null,facing='user',camOn=true,micOn=true,starting=false;
  const money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(n);
  const db=()=>typeof sb!=='undefined'?sb:null;
  async function me(){try{return (await db()?.auth.getSession())?.data?.session?.user||null}catch{return null}}
  function css(){if(document.getElementById('vLiveCss'))return;const s=document.createElement('style');s.id='vLiveCss';s.textContent=`.vLiveSheet{position:fixed;inset:0;z-index:220;background:#000e;display:none;align-items:flex-end}.vLiveSheet.on{display:flex}.vLivePanel{width:min(760px,100%);max-height:96vh;overflow:auto;background:#090909;color:#fff;border:2px solid #7b5d1d;border-radius:26px 26px 0 0;padding:14px;margin:auto 0 0}.vLiveHead{display:flex;align-items:center;gap:8px}.vLiveHead b{font-size:22px}.vLiveStatus{font-size:11px;border:1px solid #666;border-radius:999px;padding:5px 8px;color:#ddd}.vLiveStatus.live{background:#a80e28;border-color:#ff5c70;color:#fff}.vLiveClose{margin-left:auto;border:1px solid #795f22;background:#171717;color:#fff;border-radius:50%;width:44px;height:44px;font-size:23px}.vLiveStage{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.vLivePane{position:relative;aspect-ratio:9/16;max-height:54vh;border:2px solid #6f541c;border-radius:18px;overflow:hidden;background:#090909;display:grid;place-items:center}.vLivePane video{width:100%;height:100%;object-fit:cover;background:#000}.vLiveLabel{position:absolute;left:8px;top:8px;z-index:2;background:#000a;border-radius:999px;padding:6px 9px;font-size:12px}.vLiveEmpty{text-align:center;color:#c9b98b;padding:14px}.vLiveControls{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:10px 0}.vLiveControls button,.vLiveActions button{border:1px solid #66521e;border-radius:12px;padding:10px 8px;font-weight:900;background:#171717;color:#fff}.vLiveControls button.off{background:#3b161b;color:#ff9cab}.vLiveActions{display:flex;gap:8px;margin:8px 0}.vLiveStart{background:#d72a43!important;flex:1}.vLiveEnd{background:#342020!important;color:#ff9cab!important}.vLiveGiftTitle{font-weight:900;color:#f3d36c;margin:14px 0 8px}.vGiftGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.vGift{border:1px solid #72591f;background:#151515;color:#fff;border-radius:14px;padding:9px 5px;text-align:center}.vGift .i{font-size:27px}.vGift b{display:block;font-size:12px}.vGift small{display:block;color:#f1ce61;font-weight:900}.vLiveNote{font-size:11px;color:#bcae84;line-height:1.4;margin-top:10px;border:1px dashed #66521e;border-radius:12px;padding:9px}.vLiveToast{position:fixed;z-index:240;left:50%;top:16%;transform:translateX(-50%) scale(.9);background:#151515;border:2px solid #D4AF37;color:#fff;border-radius:18px;padding:14px 18px;opacity:0;pointer-events:none;transition:.2s;text-align:center;max-width:88%}.vLiveToast.on{opacity:1;transform:translateX(-50%) scale(1)}@media(max-width:430px){.vGiftGrid{grid-template-columns:repeat(2,1fr)}.vLiveControls{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(s)}
  function build(){if(document.getElementById('vLiveSheet'))return;css();const w=document.createElement('div');w.id='vLiveSheet';w.className='vLiveSheet';w.innerHTML=`<section class="vLivePanel"><div class="vLiveHead"><span>🔴</span><b>V Sosyal Canlı Yayın</b><span id="vLiveStatus" class="vLiveStatus">Hazır</span><button class="vLiveClose">✕</button></div><div class="vLiveStage"><div class="vLivePane"><span class="vLiveLabel">Yayıncı</span><video id="vLiveMe" playsinline muted autoplay></video><div class="vLiveEmpty" id="vLiveMeEmpty">📷<br>Kamera açılıyor…</div></div><div class="vLivePane"><span class="vLiveLabel">Konuk</span><div class="vLiveEmpty">👤<br>Konuk yayıncı bekleniyor</div></div></div><div class="vLiveControls"><button id="vLiveCam">📷 Kamera</button><button id="vLiveMic">🎙️ Mikrofon</button><button id="vLiveFlip">🔄 Kamerayı Çevir</button><button id="vLivePreview">👁️ Önizleme</button></div><div class="vLiveActions"><button class="vLiveStart" id="vLiveStart">🔴 Canlı Yayını Başlat</button><button class="vLiveEnd" id="vLiveEnd">⏹ Bitir</button></div><div class="vLiveGiftTitle">🎁 Canlı Yayın Hediyeleri</div><div class="vGiftGrid">${gifts.map(g=>`<button class="vGift" data-gift="${g.code}"><span class="i">${g.icon}</span><b>${g.name}</b><small>${money(g.tl)}</small></button>`).join('')}</div><div class="vLiveNote">Test modudur. Kamera ve mikrofon çalışır; gerçek para tahsilatı kapalıdır.</div></section>`;document.body.appendChild(w);const t=document.createElement('div');t.id='vLiveToast';t.className='vLiveToast';document.body.appendChild(t);w.querySelector('.vLiveClose').onclick=close;w.querySelector('#vLiveStart').onclick=start;w.querySelector('#vLiveEnd').onclick=end;w.querySelector('#vLiveCam').onclick=toggleCam;w.querySelector('#vLiveMic').onclick=toggleMic;w.querySelector('#vLiveFlip').onclick=flipCamera;w.querySelector('#vLivePreview').onclick=preview;w.querySelectorAll('[data-gift]').forEach(b=>b.onclick=()=>flash('🎁 '+b.textContent.trim()+' — test modu, ücret alınmaz.'))}
  function flash(x){const e=document.getElementById('vLiveToast');if(!e)return;e.textContent=x;e.classList.add('on');clearTimeout(window.__vlt);window.__vlt=setTimeout(()=>e.classList.remove('on'),2400)}
  function status(x,live=false){const e=document.getElementById('vLiveStatus');if(e){e.textContent=x;e.classList.toggle('live',live)}}
  function sync(){const c=document.getElementById('vLiveCam'),m=document.getElementById('vLiveMic');if(c){c.classList.toggle('off',!camOn);c.textContent=camOn?'📷 Kamera Açık':'🚫 Kamera Kapalı'}if(m){m.classList.toggle('off',!micOn);m.textContent=micOn?'🎙️ Mikrofon Açık':'🔇 Mikrofon Kapalı'}}
  async function ensureMedia(){if(!navigator.mediaDevices?.getUserMedia)throw new Error('unsupported');if(stream&&stream.active)return stream;stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing}},audio:{echoCancellation:true,noiseSuppression:true}});const v=document.getElementById('vLiveMe');v.srcObject=stream;await v.play().catch(()=>{});const e=document.getElementById('vLiveMeEmpty');if(e)e.style.display='none';camOn=true;micOn=true;sync();return stream}
  function mediaError(e){const n=e?.name||'';if(n==='NotAllowedError'||n==='PermissionDeniedError')flash('Kamera ve mikrofon iznine İzin Ver seçin.');else if(n==='NotFoundError')flash('Kamera veya mikrofon bulunamadı.');else if(n==='NotReadableError')flash('Kamera başka uygulama tarafından kullanılıyor olabilir.');else flash('Kamera açılamadı. Tarayıcı site izinlerini kontrol edin.')}
  async function open(){build();document.getElementById('vLiveSheet').classList.add('on');status('Kamera açılıyor');try{await ensureMedia();status('Kamera hazır');flash('Kamera ve mikrofon hazır.')}catch(e){status('İzin gerekli');mediaError(e)}}
  async function preview(){try{await ensureMedia();status('Kamera hazır');flash('Kamera ve mikrofon hazır.')}catch(e){mediaError(e)}}
  async function start(){if(starting)return;starting=true;try{await ensureMedia();status('CANLI',true);const user=await me();if(user&&db()){try{const r=await db().from('vitrin_live_rooms').insert({host_id:user.id,title:'VİTRİN Canlı',status:'live'}).select().single();if(!r.error)currentRoom=r.data}catch{}}flash(user?'🔴 Canlı yayın odası açıldı.':'🔴 Kamera canlı yayın test modunda çalışıyor.')}catch(e){mediaError(e)}finally{starting=false}}
  function toggleCam(){if(!stream){preview();return}camOn=!camOn;stream.getVideoTracks().forEach(t=>t.enabled=camOn);sync()}
  function toggleMic(){if(!stream){preview();return}micOn=!micOn;stream.getAudioTracks().forEach(t=>t.enabled=micOn);sync()}
  async function flipCamera(){try{facing=facing==='user'?'environment':'user';if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}await ensureMedia();flash(facing==='environment'?'Arka kamera açıldı.':'Ön kamera açıldı.')}catch(e){mediaError(e)}}
  async function end(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}const v=document.getElementById('vLiveMe');if(v)v.srcObject=null;const e=document.getElementById('vLiveMeEmpty');if(e){e.style.display='block';e.innerHTML='📷<br>Kamera kapalı'}if(currentRoom&&db()){try{await db().from('vitrin_live_rooms').update({status:'ended',ended_at:new Date().toISOString()}).eq('id',currentRoom.id)}catch{}currentRoom=null}status('Bitti');flash('Yayın bitirildi.')}
  function close(){document.getElementById('vLiveSheet')?.classList.remove('on')}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-v-live]');if(!b)return;e.preventDefault();e.stopPropagation();open()},true);
  window.openVitrinLive=open;
})();