(function(){
  if(window.__vitrinLiveV1)return;window.__vitrinLiveV1=true;
  const gifts=[
    {code:'gul',icon:'🌹',name:'Gül',tl:100},
    {code:'kahve',icon:'☕',name:'Kahve',tl:250},
    {code:'kalp',icon:'💖',name:'Parlayan Kalp',tl:500},
    {code:'yildiz',icon:'⭐',name:'Altın Yıldız',tl:1000},
    {code:'taç',icon:'👑',name:'Altın Taç',tl:2500},
    {code:'roket',icon:'🚀',name:'VİTRİN Roketi',tl:5000},
    {code:'elmas',icon:'💎',name:'Mavi Elmas',tl:10000},
    {code:'kraliyet',icon:'👑💎',name:'Kraliyet Elması',tl:25000}
  ];
  let stream=null,currentRoom=null;
  const money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(n);
  function db(){return typeof sb!=='undefined'?sb:null}
  async function me(){try{return (await db()?.auth.getSession())?.data?.session?.user||null}catch{return null}}
  function css(){if(document.getElementById('vLiveCss'))return;const s=document.createElement('style');s.id='vLiveCss';s.textContent=`
  .vLiveLaunch{width:100%;border:2px solid #8d1e2f;border-radius:18px;background:linear-gradient(135deg,#1c090d,#3c1118);color:#fff;padding:16px;margin:0 0 14px;text-align:left;box-shadow:0 10px 26px #0005}.vLiveLaunch b{display:block;font-size:20px;color:#ff6b7e;margin-bottom:4px}.vLiveLaunch small{color:#e8b7bf}.vLiveLaunch .go{float:right;font-size:24px}
  .vLiveSheet{position:fixed;inset:0;z-index:220;background:#000d;display:none;align-items:flex-end}.vLiveSheet.on{display:flex}.vLivePanel{width:min(760px,100%);max-height:94vh;overflow:auto;background:#090909;color:#fff;border:2px solid #7b5d1d;border-radius:26px 26px 0 0;padding:14px;margin:auto 0 0}.vLiveHead{display:flex;align-items:center;gap:8px}.vLiveHead b{font-size:23px}.vLiveClose{margin-left:auto;border:1px solid #795f22;background:#171717;color:#fff;border-radius:50%;width:46px;height:46px;font-size:24px}.vLiveStage{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.vLivePane{position:relative;aspect-ratio:9/16;max-height:54vh;border:2px solid #6f541c;border-radius:18px;overflow:hidden;background:radial-gradient(circle at 50% 30%,#303030,#080808);display:grid;place-items:center}.vLivePane video{width:100%;height:100%;object-fit:cover}.vLiveLabel{position:absolute;left:8px;top:8px;background:#000a;border-radius:999px;padding:6px 9px;font-size:12px}.vLiveGuestEmpty{text-align:center;color:#c9b98b;padding:14px}.vLiveActions{display:flex;gap:8px;margin:10px 0;flex-wrap:wrap}.vLiveActions button{border:0;border-radius:12px;padding:10px 12px;font-weight:900}.vLiveStart{background:#d72a43;color:#fff}.vLiveGuest{background:#D4AF37;color:#111}.vLiveEnd{background:#342020;color:#ff9cab}.vLiveGiftTitle{font-weight:900;color:#f3d36c;margin:14px 0 8px}.vGiftTargets{display:flex;gap:8px;margin-bottom:8px}.vGiftTargets button{flex:1;border:1px solid #72591f;background:#151515;color:#fff;border-radius:12px;padding:9px}.vGiftTargets button.on{background:#D4AF37;color:#111}.vGiftGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.vGift{border:1px solid #72591f;background:#151515;color:#fff;border-radius:14px;padding:9px 5px;text-align:center}.vGift .i{font-size:27px}.vGift b{display:block;font-size:12px;margin-top:3px}.vGift small{display:block;color:#f1ce61;font-weight:900;margin-top:3px}.vLiveNote{font-size:11px;color:#bcae84;line-height:1.4;margin-top:10px;border:1px dashed #66521e;border-radius:12px;padding:9px}.vLiveToast{position:fixed;z-index:240;left:50%;top:16%;transform:translateX(-50%) scale(.9);background:#151515;border:2px solid #D4AF37;color:#fff;border-radius:18px;padding:14px 18px;opacity:0;pointer-events:none;transition:.2s;text-align:center}.vLiveToast.on{opacity:1;transform:translateX(-50%) scale(1)}
  @media(max-width:430px){.vGiftGrid{grid-template-columns:repeat(2,1fr)}.vLivePanel{padding:12px}.vLiveHead b{font-size:21px}}
  `;document.head.appendChild(s)}
  function build(){if(document.getElementById('vLiveSheet'))return;css();const w=document.createElement('div');w.id='vLiveSheet';w.className='vLiveSheet';w.innerHTML=`<section class="vLivePanel"><div class="vLiveHead"><span>🔴</span><b>V Sosyal Canlı Yayın</b><button class="vLiveClose">✕</button></div><div class="vLiveStage"><div class="vLivePane"><span class="vLiveLabel">Yayıncı</span><video id="vLiveMe" playsinline muted></video><div class="vLiveGuestEmpty" id="vLiveMeEmpty">Kameranız kapalı</div></div><div class="vLivePane"><span class="vLiveLabel">Konuk</span><div class="vLiveGuestEmpty">👤<br>Konuk yayıncı bekleniyor</div></div></div><div class="vLiveActions"><button class="vLiveStart" id="vLiveStart">📹 Canlı Yayını Başlat</button><button class="vLiveGuest" id="vLiveGuest">➕ Konuk Davet Et</button><button class="vLiveEnd" id="vLiveEnd">⏹ Yayını Bitir</button></div><div class="vLiveGiftTitle">🎁 Canlı Yayın Hediyeleri</div><div class="vGiftTargets"><button class="on" data-target="host">Yayıncıya</button><button data-target="guest">Konuk yayıncıya</button></div><div class="vGiftGrid">${gifts.map(g=>`<button class="vGift" data-gift="${g.code}"><span class="i">${g.icon}</span><b>${g.name}</b><small>${money(g.tl)}</small></button>`).join('')}</div><div class="vLiveNote">Ödeme güvenliği: kart ve banka bilgileri VİTRİN içinde saklanmaz. Gerçek ücret tahsilatı ve yayıncıya banka ödemesi, lisanslı ödeme kuruluşu üzerinden yapılacaktır. Ödeme sağlayıcısı bağlanana kadar hediye tuşları gerçek para çekmez.</div></section>`;document.body.appendChild(w);const toast=document.createElement('div');toast.id='vLiveToast';toast.className='vLiveToast';document.body.appendChild(toast);
    w.querySelector('.vLiveClose').onclick=close;w.addEventListener('click',e=>{if(e.target===w)close()});w.querySelector('#vLiveStart').onclick=start;w.querySelector('#vLiveEnd').onclick=end;w.querySelector('#vLiveGuest').onclick=()=>flash('Konuk daveti altyapısı hazırlanıyor.');w.querySelectorAll('.vGiftTargets button').forEach(b=>b.onclick=()=>{w.querySelectorAll('.vGiftTargets button').forEach(x=>x.classList.remove('on'));b.classList.add('on')});w.querySelectorAll('[data-gift]').forEach(b=>b.onclick=()=>gift(b.dataset.gift));
  }
  function flash(t){const e=document.getElementById('vLiveToast');if(!e)return;e.textContent=t;e.classList.add('on');clearTimeout(window.__vlt);window.__vlt=setTimeout(()=>e.classList.remove('on'),2200)}
  async function open(){build();document.getElementById('vLiveSheet').classList.add('on')}
  async function start(){const user=await me();if(!user){flash('Canlı yayın için giriş yapmalısınız.');return}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:true});const v=document.getElementById('vLiveMe');v.srcObject=stream;await v.play();document.getElementById('vLiveMeEmpty').style.display='none';const client=db();if(client){const r=await client.from('vitrin_live_rooms').insert({host_id:user.id,title:'VİTRİN Canlı',status:'live'}).select().single();if(!r.error)currentRoom=r.data}flash('🔴 Canlı yayın odası açıldı.')}catch(e){flash('Kamera/mikrofon izni gerekli.') }}
  async function end(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}const v=document.getElementById('vLiveMe');if(v)v.srcObject=null;const emp=document.getElementById('vLiveMeEmpty');if(emp)emp.style.display='block';if(currentRoom&&db()){await db().from('vitrin_live_rooms').update({status:'ended',ended_at:new Date().toISOString()}).eq('id',currentRoom.id);currentRoom=null}flash('Yayın bitirildi.')}
  async function gift(code){const g=gifts.find(x=>x.code===code);if(!g)return;const user=await me();if(!user){flash('Hediye göndermek için giriş yapmalısınız.');return}const target=document.querySelector('.vGiftTargets button.on')?.dataset.target||'host';if(!currentRoom){flash('Önce aktif bir canlı yayına girin.');return}const recipient=target==='guest'?currentRoom.guest_id:currentRoom.host_id;if(!recipient){flash('Bu tarafta henüz yayıncı yok.');return}if(user.id===recipient){flash('Kendinize hediye gönderemezsiniz.');return}flash(`${g.icon} ${g.name} · ${money(g.tl)} — ödeme sağlayıcısı bağlandıktan sonra tahsil edilecek.`)}
  function close(){document.getElementById('vLiveSheet')?.classList.remove('on')}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-v-live]');if(!b)return;e.preventDefault();e.stopPropagation();open()},true);
  window.openVitrinLive=open;
})();