(function(){
  if(window.__vitrinLiveV2)return;window.__vitrinLiveV2=true;
  const gifts=[
    {code:'gul',icon:'🌹',name:'Gül',tl:100},{code:'kahve',icon:'☕',name:'Kahve',tl:250},{code:'kalp',icon:'💖',name:'Parlayan Kalp',tl:500},{code:'yildiz',icon:'⭐',name:'Altın Yıldız',tl:1000},{code:'tac',icon:'👑',name:'Altın Taç',tl:2500},{code:'roket',icon:'🚀',name:'VİTRİN Roketi',tl:5000},{code:'elmas',icon:'💎',name:'Mavi Elmas',tl:10000},{code:'kraliyet',icon:'👑💎',name:'Kraliyet Elması',tl:25000}
  ];
  let stream=null,currentRoom=null,facing='user',micOn=true,camOn=true,starting=false;
  const money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(n);
  function db(){return typeof sb!=='undefined'?sb:null}
  async function me(){try{return (await db()?.auth.getSession())?.data?.session?.user||null}catch{return null}}
  function css(){if(document.getElementById('vLiveCss'))return;const s=document.createElement('style');s.id='vLiveCss';s.textContent=`
  .vLiveSheet{position:fixed;inset:0;z-index:220;background:#000e;display:none;align-items:flex-end}.vLiveSheet.on{display:flex}.vLivePanel{width:min(760px,100%);max-height:96vh;overflow:auto;background:#090909;color:#fff;border:2px solid #7b5d1d;border-radius:26px 26px 0 0;padding:14px;margin:auto 0 0}.vLiveHead{display:flex;align-items:center;gap:8px}.vLiveHead b{font-size:23px}.vLiveStatus{margin-left:6px;font-size:11px;border:1px solid #5b5b5b;border-radius:999px;padding:5px 8px;color:#ccc}.vLiveStatus.live{background:#a80e28;border-color:#ff5c70;color:#fff}.vLiveClose{margin-left:auto;border:1px solid #795f22;background:#171717;color:#fff;border-radius:50%;width:44px;height:44px;font-size:23px}.vLiveStage{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.vLivePane{position:relative;aspect-ratio:9/16;max-height:54vh;border:2px solid #6f541c;border-radius:18px;overflow:hidden;background:radial-gradient(circle at 50% 30%,#303030,#080808);display:grid;place-items:center}.vLivePane video{width:100%;height:100%;object-fit:cover;background:#000}.vLiveLabel{position:absolute;left:8px;top:8px;z-index:2;background:#000a;border-radius:999px;padding:6px 9px;font-size:12px}.vLiveGuestEmpty{text-align:center;color:#c9b98b;padding:14px}.vLiveControls{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:10px 0}.vLiveControls button,.vLiveActions button{border:1px solid #66521e;border-radius:12px;padding:10px 8px;font-weight:900;background:#171717;color:#fff}.vLiveControls button.off{background:#3b161b;color:#ff9cab;border-color:#7b2834}.vLiveActions{display:flex;gap:8px;margin:8px 0;flex-wrap:wrap}.vLiveStart{background:#d72a43!important;color:#fff!important;flex:1}.vLiveGuest{background:#D4AF37!important;color:#111!important;flex:1}.vLiveEnd{background:#342020!important;color:#ff9cab!important}.vLiveGiftTitle{font-weight:900;color:#f3d36c;margin:14px 0 8px}.vGiftTargets{display:flex;gap:8px;margin-bottom:8px}.vGiftTargets button{flex:1;border:1px solid #72591f;background:#151515;color:#fff;border-radius:12px;padding:9px}.vGiftTargets button.on{background:#D4AF37;color:#111}.vGiftGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.vGift{border:1px solid #72591f;background:#151515;color:#fff;border-radius:14px;padding:9px 5px;text-align:center}.vGift .i{font-size:27px}.vGift b{display:block;font-size:12px;margin-top:3px}.vGift small{display:block;color:#f1ce61;font-weight:900;margin-top:3px}.vLiveNote{font-size:11px;color:#bcae84;line-height:1.4;margin-top:10px;border:1px dashed #66521e;border-radius:12px;padding:9px}.vLiveToast{position:fixed;z-index:240;left:50%;top:16%;transform:translateX(-50%) scale(.9);background:#151515;border:2px solid #D4AF37;color:#fff;border-radius:18px;padding:14px 18px;opacity:0;pointer-events:none;transition:.2s;text-align:center;max-width:88%}.vLiveToast.on{opacity:1;transform:translateX(-50%) scale(1)}
  @media(max-width:430px){.vGiftGrid{grid-template-columns:repeat(2,1fr)}.vLivePanel{padding:12px}.vLiveHead b{font-size:20px}.vLiveControls{grid-template-columns:repeat(2,1fr)}}` ;document.head.appendChild(s)}
  function build(){if(document.getElementById('vLiveSheet'))return;css();const w=document.createElement('div');w.id='vLiveSheet';w.className='vLiveSheet';w.innerHTML=`<section class="vLivePanel"><div class="vLiveHead"><span>🔴</span><b>V Sosyal Canlı Yayın</b><span id="vLiveStatus" class="vLiveStatus">Hazır</span><button class="vLiveClose">✕</button></div><div class="vLiveStage"><div class="vLivePane"><span class="vLiveLabel">Yayıncı</span><video id="vLiveMe" playsinline muted autoplay></video><div class="vLiveGuestEmpty" id="vLiveMeEmpty">📷<br>Kamera kapalı</div></div><div class="vLivePane"><span class="vLiveLabel">Konuk</span><video id="vLiveGuestVideo" playsinline autoplay></video><div class="vLiveGuestEmpty" id="vLiveGuestEmpty">👤<br>Konuk yayıncı bekleniyor</div></div></div><div class="vLiveControls"><button id="vLiveCam">📷 Kamera</button><button id="vLiveMic">🎙️ Mikrofon</button><button id="vLiveFlip">🔄 Kamerayı Çevir</button><button id="vLivePreview">👁️ Önizleme</button></div><div class="vLiveActions"><button class="vLiveStart" id="vLiveStart">🔴 Canlı Yayını Başlat</button><button class="vLiveGuest" id="vLiveGuest">➕ Konuk Davet Et</button><button class="vLiveEnd" id="vLiveEnd">⏹ Bitir</button></div><div class="vLiveGiftTitle">🎁 Canlı Yayın Hediyeleri</div><div class="vGiftTargets"><button class="on" data-target="host">Yayıncıya</button><button data-target="guest">Konuk yayıncıya</button></div><div class="vGiftGrid">${gifts.map(g=>`<button class="vGift" data-gift="${g.code}"><span class="i">${g.icon}</span><b>${g.name}</b><small>${money(g.tl)}</small></button>`).join('')}</div><div class="vLiveNote">Bu kopya test modundadır. Kamera ve mikrofon cihazınızda çalışır; gerçek para tahsilatı kapalıdır. Kart/banka bilgisi VİTRİN içinde saklanmaz.</div></section>`;document.body.appendChild(w);const toast=document.createElement('div');toast.id='vLiveToast';toast.className='vLiveToast';document.body.appendChild(toast);
    w.querySelector('.vLiveClose').onclick=close;w.addEventListener('click',e=>{if(e.target===w)close()});w.querySelector('#vLiveStart').onclick=start;w.querySelector('#vLiveEnd').onclick=end;w.querySelector('#vLiveCam').onclick=toggleCam;w.querySelector('#vLiveMic').onclick=toggleMic;w.querySelector('#vLiveFlip').onclick=flipCamera;w.querySelector('#vLivePreview').onclick=preview;w.querySelector('#vLiveGuest').onclick=guestInvite;w.querySelectorAll('.vGiftTargets button').forEach(b=>b.onclick=()=>{w.querySelectorAll('.vGiftTargets button').forEach(x=>x.classList.remove('on'));b.classList.add('on')});w.querySelectorAll('[data-gift]').forEach(b=>b.onclick=()=>gift(b.dataset.gift));
  }
  function flash(t){const e=document.getElementById('vLiveToast');if(!e)return;e.textContent=t;e.classList.add('on');clearTimeout(window.__vlt);window.__vlt=setTimeout(()=>e.classList.remove('on'),2400)}
  function status(text,live){const e=document.getElementById('vLiveStatus');if(!e)return;e.textContent=text;e.classList.toggle('live',!!live)}
  async function ensureMedia(){if(!navigator.mediaDevices?.getUserMedia)throw new Error('unsupported');if(stream&&stream.active)return stream;stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:1280},height:{ideal:720}},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const v=document.getElementById('vLiveMe');if(v){v.srcObject=stream;await v.play().catch(()=>{})}document.getElementById('vLiveMeEmpty').style.display='none';camOn=true;micOn=true;syncButtons();return stream}
  function syncButtons(){const c=document.getElementById('vLiveCam'),m=document.getElementById('vLiveMic');if(c){c.classList.toggle('off',!camOn);c.textContent=camOn?'📷 Kamera Açık':'🚫 Kamera Kapalı'}if(m){m.classList.toggle('off',!micOn);m.textContent=micOn?'🎙️ Mikrofon Açık':'🔇 Mikrofon Kapalı'}}
  async function open(){build();document.getElementById('vLiveSheet').classList.add('on');status(stream?.active?'Kamera hazır':'Hazır',false)}
  async function preview(){try{await ensureMedia();status('Kamera hazır',false);flash('Kamera ve mikrofon hazır.')}catch(e){mediaError(e)}}
  async function start(){if(starting)return;starting=true;try{const user=await me();if(!user){flash('Canlı yayın için giriş yapmalısınız.');return}await ensureMedia();status('CANLI',true);const client=db();if(client){try{const r=await client.from('vitrin_live_rooms').insert({host_id:user.id,title:'VİTRİN Canlı',status:'live'}).select().single();if(!r.error)currentRoom=r.data}catch{}}flash('🔴 Kamera yayına hazır. Canlı oda açıldı.')}catch(e){mediaError(e)}finally{starting=false}}
  function mediaError(e){const n=e?.name||'';if(n==='NotAllowedError'||n==='PermissionDeniedError')flash('Kamera ve mikrofon iznine izin verin.');else if(n==='NotFoundError'||n==='DevicesNotFoundError')flash('Kamera veya mikrofon bulunamadı.');else if(n==='NotReadableError')flash('Kamera başka bir uygulama tarafından kullanılıyor olabilir.');else if(location.protocol!=='https:'&&location.hostname!=='localhost')flash('Kamera için HTTPS bağlantısı gerekli.');else flash('Kamera açılamadı. Tarayıcı izinlerini kontrol edin.')}
  function toggleCam(){if(!stream){preview();return}const tracks=stream.getVideoTracks();camOn=!camOn;tracks.forEach(t=>t.enabled=camOn);syncButtons();flash(camOn?'Kamera açıldı.':'Kamera kapatıldı.')}
  function toggleMic(){if(!stream){preview();return}const tracks=stream.getAudioTracks();micOn=!micOn;tracks.forEach(t=>t.enabled=micOn);syncButtons();flash(micOn?'Mikrofon açıldı.':'Mikrofon sessize alındı.')}
  async function flipCamera(){if(!stream){facing=facing==='user'?'environment':'user';await preview();return}const old=stream;const oldAudio=old.getAudioTracks()[0]||null;try{facing=facing==='user'?'environment':'user';const ns=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing}},audio:false});const newVideo=ns.getVideoTracks()[0];old.getVideoTracks().forEach(t=>t.stop());const combined=new MediaStream();combined.addTrack(newVideo);if(oldAudio)combined.addTrack(oldAudio);stream=combined;const v=document.getElementById('vLiveMe');v.srcObject=stream;await v.play().catch(()=>{});camOn=true;syncButtons();flash(facing==='environment'?'Arka kamera açıldı.':'Ön kamera açıldı.')}catch(e){facing=facing==='user'?'environment':'user';flash('Bu cihazda kamera değiştirilemedi.')}}
  async function guestInvite(){if(!currentRoom){flash('Önce canlı yayını başlatın.');return}const code=String(currentRoom.id||'').slice(0,8);try{if(navigator.share)await navigator.share({title:'VİTRİN Canlı Yayın',text:`VİTRİN canlı yayın daveti ${code}`,url:location.href});else if(navigator.clipboard){await navigator.clipboard.writeText(location.href);flash('Yayın bağlantısı kopyalandı.')}}catch{}}
  async function end(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}const v=document.getElementById('vLiveMe');if(v)v.srcObject=null;const emp=document.getElementById('vLiveMeEmpty');if(emp)emp.style.display='block';if(currentRoom&&db()){try{await db().from('vitrin_live_rooms').update({status:'ended',ended_at:new Date().toISOString()}).eq('id',currentRoom.id)}catch{}currentRoom=null}status('Bitti',false);camOn=true;micOn=true;syncButtons();flash('Yayın bitirildi.')}
  async function gift(code){const g=gifts.find(x=>x.code===code);if(!g)return;const user=await me();if(!user){flash('Hediye göndermek için giriş yapmalısınız.');return}const target=document.querySelector('.vGiftTargets button.on')?.dataset.target||'host';if(!currentRoom){flash('Önce aktif bir canlı yayına girin.');return}const recipient=target==='guest'?currentRoom.guest_id:currentRoom.host_id;if(!recipient){flash('Bu tarafta henüz yayıncı yok.');return}if(user.id===recipient){flash('Kendinize hediye gönderemezsiniz.');return}flash(`${g.icon} ${g.name} · ${money(g.tl)} — test modu, gerçek ücret alınmaz.`)}
  function close(){document.getElementById('vLiveSheet')?.classList.remove('on')}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-v-live]');if(!b)return;e.preventDefault();e.stopPropagation();open()},true);
  window.openVitrinLive=open;
})();
