(function(){
  if(window.__vitrinI18n)return;window.__vitrinI18n=true;
  const STORE='vitrin_language_v1';
  const LANGS=[
    ['tr','🇹🇷','Türkçe'],['en','🇬🇧','English'],['de','🇩🇪','Deutsch'],['fr','🇫🇷','Français'],['es','🇪🇸','Español'],['it','🇮🇹','Italiano'],['pt','🇵🇹','Português'],['ru','🇷🇺','Русский'],['uk','🇺🇦','Українська'],['ar','🇸🇦','العربية'],['fa','🇮🇷','فارسی'],['he','🇮🇱','עברית'],['az','🇦🇿','Azərbaycanca'],['kk','🇰🇿','Қазақша'],['uz','🇺🇿','O‘zbekcha'],['tk','🇹🇲','Türkmençe'],['ky','🇰🇬','Кыргызча'],['hy','🇦🇲','Հայերեն'],['ka','🇬🇪','ქართული'],['el','🇬🇷','Ελληνικά'],['bg','🇧🇬','Български'],['ro','🇷🇴','Română'],['hu','🇭🇺','Magyar'],['pl','🇵🇱','Polski'],['cs','🇨🇿','Čeština'],['sk','🇸🇰','Slovenčina'],['sl','🇸🇮','Slovenščina'],['hr','🇭🇷','Hrvatski'],['sr','🇷🇸','Српски'],['bs','🇧🇦','Bosanski'],['sq','🇦🇱','Shqip'],['mk','🇲🇰','Македонски'],['nl','🇳🇱','Nederlands'],['da','🇩🇰','Dansk'],['sv','🇸🇪','Svenska'],['no','🇳🇴','Norsk'],['fi','🇫🇮','Suomi'],['is','🇮🇸','Íslenska'],['et','🇪🇪','Eesti'],['lv','🇱🇻','Latviešu'],['lt','🇱🇹','Lietuvių'],['ga','🇮🇪','Gaeilge'],['cy','🏴','Cymraeg'],['mt','🇲🇹','Malti'],['eu','🏳️','Euskara'],['ca','🏴','Català'],['gl','🏳️','Galego'],['af','🇿🇦','Afrikaans'],['sw','🇰🇪','Kiswahili'],['am','🇪🇹','አማርኛ'],['so','🇸🇴','Soomaali'],['zu','🇿🇦','isiZulu'],['xh','🇿🇦','isiXhosa'],['st','🇱🇸','Sesotho'],['ha','🇳🇬','Hausa'],['yo','🇳🇬','Yorùbá'],['ig','🇳🇬','Igbo'],['rw','🇷🇼','Kinyarwanda'],['mg','🇲🇬','Malagasy'],['sn','🇿🇼','Shona'],['ny','🇲🇼','Chichewa'],['ps','🇦🇫','پښتو'],['ur','🇵🇰','اردو'],['hi','🇮🇳','हिन्दी'],['bn','🇧🇩','বাংলা'],['pa','🇮🇳','ਪੰਜਾਬੀ'],['gu','🇮🇳','ગુજરાતી'],['mr','🇮🇳','मराठी'],['ne','🇳🇵','नेपाली'],['si','🇱🇰','සිංහල'],['ta','🇮🇳','தமிழ்'],['te','🇮🇳','తెలుగు'],['kn','🇮🇳','ಕನ್ನಡ'],['ml','🇮🇳','മലയാളം'],['or','🇮🇳','ଓଡ଼ିଆ'],['as','🇮🇳','অসমীয়া'],['my','🇲🇲','မြန်မာ'],['th','🇹🇭','ไทย'],['lo','🇱🇦','ລາວ'],['km','🇰🇭','ខ្មែរ'],['vi','🇻🇳','Tiếng Việt'],['id','🇮🇩','Bahasa Indonesia'],['ms','🇲🇾','Bahasa Melayu'],['tl','🇵🇭','Filipino'],['jv','🇮🇩','Basa Jawa'],['su','🇮🇩','Basa Sunda'],['zh-CN','🇨🇳','简体中文'],['zh-TW','🇹🇼','繁體中文'],['ja','🇯🇵','日本語'],['ko','🇰🇷','한국어'],['mn','🇲🇳','Монгол'],['ceb','🇵🇭','Cebuano'],['hmn','🏳️','Hmong'],['haw','🇺🇸','Hawaiian'],['mi','🇳🇿','Māori'],['sm','🇼🇸','Samoan'],['ht','🇭🇹','Kreyòl Ayisyen'],['la','🏛️','Latina'],['eo','🌍','Esperanto'],['lb','🇱🇺','Lëtzebuergesch'],['be','🇧🇾','Беларуская'],['yi','🏳️','ייִדיש'],['ku','🏳️','Kurdî'],['sd','🇵🇰','سنڌي'],['tg','🇹🇯','Тоҷикӣ']
  ];
  let wanted=localStorage.getItem(STORE)||'tr',ready=false;
  function addStyle(){if(document.getElementById('vI18nStyle'))return;const s=document.createElement('style');s.id='vI18nStyle';s.textContent=`.vLangBtn{width:42px;height:42px;border:2px solid var(--vt-accent2,#73591e)!important;border-radius:14px;background:#171717;color:#fff;font-size:20px;display:grid;place-items:center}.vLangPanel{position:fixed;inset:0;z-index:12000;background:#000d;display:none;align-items:flex-end;justify-content:center}.vLangPanel.on{display:flex}.vLangSheet{width:min(620px,100%);max-height:90vh;background:#0b0b0b;border:2px solid #73591e;border-radius:24px 24px 0 0;padding:14px;color:#fff}.vLangHead{display:flex;align-items:center;gap:8px}.vLangHead b{font-size:19px}.vLangClose{margin-left:auto;width:40px;height:40px;border:1px solid #73591e;border-radius:50%;background:#171717;color:#fff;font-size:20px}.vLangSearch{width:100%;margin:12px 0;padding:12px;border:1px solid #73591e;border-radius:13px;background:#111;color:#fff}.vLangList{display:grid;grid-template-columns:1fr 1fr;gap:7px;overflow:auto;max-height:64vh}.vLangItem{border:1px solid #5e481d;border-radius:13px;background:#151515;color:#fff;padding:10px;text-align:left;font-weight:750}.vLangItem.on{background:#D4AF37;color:#111}.vLangNote{font-size:11px;color:#baa978;margin-top:8px}.goog-te-banner-frame,.skiptranslate iframe{display:none!important}body{top:0!important}.goog-te-gadget{display:none!important}#google_translate_element{position:fixed;left:-9999px;top:-9999px;width:1px;height:1px;overflow:hidden}`;document.head.appendChild(s)}
  function build(){if(document.getElementById('vLangPanel'))return;addStyle();const p=document.createElement('div');p.id='vLangPanel';p.className='vLangPanel notranslate';p.setAttribute('translate','no');p.innerHTML=`<div class="vLangSheet"><div class="vLangHead"><span>🌐</span><b>Dil / Language</b><button class="vLangClose">✕</button></div><input class="vLangSearch" placeholder="Dil ara / Search language"><div class="vLangList"></div><div class="vLangNote">Seçiminiz bu cihazda kaydedilir. VİTRİN adı değişmez; arayüz ve içerikler seçilen dile çevrilir.</div><div id="google_translate_element"></div></div>`;document.body.appendChild(p);p.onclick=e=>{if(e.target===p)p.classList.remove('on')};p.querySelector('.vLangClose').onclick=()=>p.classList.remove('on');p.querySelector('.vLangSearch').oninput=e=>render(e.target.value);render('')}
  function render(q){const box=document.querySelector('.vLangList');if(!box)return;const t=(q||'').toLocaleLowerCase('tr-TR');const rows=LANGS.filter(x=>(x[2]+' '+x[0]).toLocaleLowerCase('tr-TR').includes(t));box.innerHTML=rows.map(x=>`<button class="vLangItem ${x[0]===wanted?'on':''}" data-lang="${x[0]}">${x[1]} ${x[2]}</button>`).join('');box.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>choose(b.dataset.lang))}
  function mount(){build();document.querySelectorAll('.vitrinBrand,.brand').forEach(x=>{x.classList.add('notranslate');x.setAttribute('translate','no')});const actions=document.querySelector('.topActions,.actions');if(actions&&!actions.querySelector('.vLangBtn')){const b=document.createElement('button');b.type='button';b.className='vLangBtn action notranslate';b.title='Dil seç';b.setAttribute('aria-label','Dil seç');b.textContent='🌐';b.onclick=()=>document.getElementById('vLangPanel').classList.add('on');actions.prepend(b)}}
  function eraseCookie(){const host=location.hostname;document.cookie='googtrans=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/';document.cookie='googtrans=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/;domain=.'+host}
  function choose(code){wanted=code;localStorage.setItem(STORE,code);if(code==='tr'){eraseCookie();location.reload();return}document.cookie='googtrans=/tr/'+code+';path=/;SameSite=Lax';apply(code);document.getElementById('vLangPanel')?.classList.remove('on');render('')}
  function apply(code){const combo=document.querySelector('.goog-te-combo');if(!combo)return false;combo.value=code;combo.dispatchEvent(new Event('change',{bubbles:true}));return true}
  window.vitrinGoogleTranslateInit=function(){try{new google.translate.TranslateElement({pageLanguage:'tr',includedLanguages:LANGS.map(x=>x[0]).join(','),autoDisplay:false,multilanguagePage:true},'google_translate_element');ready=true;setTimeout(()=>{if(wanted!=='tr')apply(wanted)},500)}catch(e){console.warn('VİTRİN dil sistemi başlatılamadı',e)}};
  function loadGoogle(){if(document.querySelector('script[data-vitrin-translate]'))return;const s=document.createElement('script');s.src='https://translate.google.com/translate_a/element.js?cb=vitrinGoogleTranslateInit';s.async=true;s.dataset.vitrinTranslate='1';document.head.appendChild(s)}
  function init(){mount();loadGoogle();const mo=new MutationObserver(()=>mount());mo.observe(document.body,{childList:true,subtree:true});setInterval(()=>{mount();if(ready&&wanted!=='tr')apply(wanted)},2500)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();